"""empty message

Revision ID: a708d1818279
Revises: 
Create Date: 2017-10-03 00:31:19.614970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a708d1818279'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adminemail', sa.String(length=50), nullable=True),
    sa.Column('noteemail', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_emails_adminemail'), 'admin_emails', ['adminemail'], unique=True)
    op.create_index(op.f('ix_admin_emails_noteemail'), 'admin_emails', ['noteemail'], unique=True)
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('item', sa.String(length=140), nullable=True),
    sa.Column('asset', sa.String(length=140), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('dueDate', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('date_returned', sa.String(length=140), nullable=True),
    sa.Column('status', sa.String(length=140), nullable=True),
    sa.Column('tech', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_duration'), 'entry', ['duration'], unique=False)
    op.create_index(op.f('ix_entry_first_name'), 'entry', ['first_name'], unique=False)
    op.create_index(op.f('ix_entry_last_name'), 'entry', ['last_name'], unique=False)
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('item', sa.String(length=140), nullable=True),
    sa.Column('action', sa.String(length=140), nullable=True),
    sa.Column('tech', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_first_name'), 'log', ['first_name'], unique=False)
    op.create_index(op.f('ix_log_last_name'), 'log', ['last_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_log_last_name'), table_name='log')
    op.drop_index(op.f('ix_log_first_name'), table_name='log')
    op.drop_table('log')
    op.drop_index(op.f('ix_entry_last_name'), table_name='entry')
    op.drop_index(op.f('ix_entry_first_name'), table_name='entry')
    op.drop_index(op.f('ix_entry_duration'), table_name='entry')
    op.drop_table('entry')
    op.drop_index(op.f('ix_admin_emails_noteemail'), table_name='admin_emails')
    op.drop_index(op.f('ix_admin_emails_adminemail'), table_name='admin_emails')
    op.drop_table('admin_emails')
    # ### end Alembic commands ###
